export const CUSTOMER_ORDERS = "CUSTOMER_ORDERS";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const CUSTOMER_LOGIN = "CUSTOMER_LOGIN";
export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT";

export const ADD_CUSTOMER_ADDRESS = "ADD_CUSTOMER_ADDRESS";

export const PLACE_ORDER = "PLACE_ORDER";

export const ORDER_CONFIRM = "ORDER_CONFIRM";
